name: Build backend and migration images
description: Build, package and distribute server and migration images via docker container images pushed to a registry

inputs:
  tag:
    description: 'Image tag'
    required: true
  aws-ecr-uri:
    description: "AWS ECR URI, similar to 'public.ecr.aws/ecr-default-alias'"
    required: true
  aws-region:
    description: "AWS REGION, similar to 'eu-central-1'"
    required: true
  aws-role-arn:
    description: 'AWS Role to assume'
    required: true

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}

    - name: Auth to the ECR
      run: bash ./docker/auth.sh ${{ inputs.aws-ecr-uri }} ${{ inputs.aws-region }}
      shell: bash

    - name: Build and push the images
      run: bash ./docker/build.sh ${{ inputs.aws-ecr-uri }} ${{ inputs.tag }}
      shell: bash
