psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE $POSTGRES_ETHERPAD_DB;
    CREATE USER $POSTGRES_ETHERPAD_USER WITH PASSWORD '$POSTGRES_ETHERPAD_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_ETHERPAD_DB to $POSTGRES_ETHERPAD_USER;
EOSQL